### ISSUE TITLE
Accessibility Consulting / Understandable |

### ISSUE THREAD

**Issue by DanieldRioG** [DanieldRioG/Mondongo#60]

**Comment by DanieldRioG** [comment]
Intentar hacer la mayor cantidad posible de AAA posible. Como margen se pueden dejar 1 o 2.

**Comment by DanielAlonsoDAW** [comment]
En 3.1 y 3.2 veo todo correcto para AAA

En 3.3 estoy casi seguro de que también, a ver si aceptan el pull request para confirmarlo en local.
